### ISSUE TITLE
Allow separate icons for SourceContainers that are disabled, or grey them out

### ISSUE THREAD

**Issue by filiptibell** [Muoshuu/rojo-ui#4]
The scripts in my game start out as disabled until my framework has loaded to guarantee loading order. Using Roblox Studio, I can see when scripts are disabled using the tree view, and they show as greyed out:

![Studio](https://i.imgur.com/l2RgPag.png)

I would like to be able to either define a custom icon when they are disabled, or to have them be greyed out the same as in studio, because this makes me think the scripts are enabled when that is something that would break my game:

![VSCode](https://i.imgur.com/q7jSKfu.png)

**Comment by jerrin-f** [comment]
Because of how VS Code's TreeView API works, this would require significant changes to how icon generation works, so I'll be putting this off for a bit while I decide on the implementation.

**Comment by jerrin-f** [comment]
As of the next version, which will be available in a few days, all disabled scripts will have a subtext appended to them as seen below. The only caveat here is that the script's disabled property must be managed by Rojo.

![image](https://user-images.githubusercontent.com/43345741/128617975-823b645a-a686-46a0-ad0f-18d4b70f26a0.png)
